### ISSUE TITLE
Is it possible to have the Dockerfile of the image? 

### ISSUE THREAD

**Issue by AwePhD** [daddydrac/Deep-Learning-Ultra#1]
Hello,

This seems to be a well-constructed Docker compose for Deep Learning. In my opinion, the set of tools is well chosen. Is it possible to have the Dockerfile from the image, please? While the image contains everything one might need, its size is 40GB. It might be useful to provide the Dockerfile details for those who want to use only certain parts of it. Additionally, the community may suggest enhancements that reduce the image size. Who knows? :)

Have a nice day,
Mathias.

**Comment by daddydrac** [comment]
No, that is not the aim of the project. However, if you would like a smaller one, tell me what specific tooling you'd like and I can compile one for GPU that supports your needs.

Actually, here is a better idea, and tell me what you think:

I build a self installer in the cli that lets you choose what you want and it assembles both a specific (user chosen) and lightweight solution for you?

**Comment by AwePhD** [comment]
That's a very interesting suggestion. 
I think it might be a good idea to have a flexible choice of tooling. It would be a very easy way to set up a deep learning environment / deployment which fits the user uses. Thanks for you answer and your time :)

Also, if you want to extend the tooling, you might be interested to add "high level" deep learning framework which are domain specific. For example, in computer vision tasks [openmmlab](https://github.com/open-mmlab). That is just an example, I use this framework. It might be any "domain" framework.  I would understand that the point of the repo is to remain general. 

Also, maybe another suggestion if I may so, it would be to be able to version the tooling suite?

**Comment by daddydrac** [comment]
I'll need to vet OpenMM Lab for security before I can commit to pulling that in any form.
